#!/usr/bin/env bash
# Deterministic Groth16 setup for the Sefi circom recipe circuits.
#
# Uses FIXED entropy + a fixed beacon so the proving key (zkey) and verification
# key (vkey) are reproducible: anyone who runs this gets the SAME vkey that is
# committed in circuits/circom/build/<circuit>.vkey.json and registered on the
# Soroban verifier. The zkey is large and gitignored; this script regenerates it.
#
#   pnpm circom:setup            # build + setup all recipe circuits
set -euo pipefail

CIRCOM_DIR="circuits/circom"
BUILD="$CIRCOM_DIR/build"
PTAU_POWER="${SEFI_PTAU_POWER:-14}"
mkdir -p "$BUILD"

if ! command -v circom >/dev/null 2>&1; then
  echo "circom not found; install circom 2.x (cargo install --git https://github.com/iden3/circom)"; exit 1
fi
SNARKJS="npx snarkjs"

# 1) One shared powers-of-tau (deterministic: fixed entropy + beacon).
PTAU="$BUILD/pot_final.ptau"
if [ ! -f "$PTAU" ]; then
  echo "== powers of tau (2^$PTAU_POWER, deterministic) =="
  $SNARKJS powersoftau new bn128 "$PTAU_POWER" "$BUILD/pot_0.ptau" -v
  $SNARKJS powersoftau contribute "$BUILD/pot_0.ptau" "$BUILD/pot_1.ptau" \
    --name="sefi-fixed" -e="sefi-deterministic-ptau-entropy"
  $SNARKJS powersoftau beacon "$BUILD/pot_1.ptau" "$BUILD/pot_beacon.ptau" \
    0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20 10 -n="sefi beacon"
  $SNARKJS powersoftau prepare phase2 "$BUILD/pot_beacon.ptau" "$PTAU" -v
  rm -f "$BUILD/pot_0.ptau" "$BUILD/pot_1.ptau" "$BUILD/pot_beacon.ptau"
fi

for CIRCUIT in blend_utilization; do
  echo "== $CIRCUIT =="
  circom "$CIRCOM_DIR/$CIRCUIT.circom" --r1cs --wasm --sym \
    -l node_modules/circomlib/circuits -o "$BUILD"
  $SNARKJS groth16 setup "$BUILD/$CIRCUIT.r1cs" "$PTAU" "$BUILD/${CIRCUIT}_0.zkey"
  $SNARKJS zkey contribute "$BUILD/${CIRCUIT}_0.zkey" "$BUILD/$CIRCUIT.zkey" \
    --name="sefi-fixed" -e="sefi-deterministic-zkey-entropy-$CIRCUIT"
  $SNARKJS zkey beacon "$BUILD/$CIRCUIT.zkey" "$BUILD/${CIRCUIT}_final.zkey" \
    0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20 10 -n="sefi zkey beacon"
  mv "$BUILD/${CIRCUIT}_final.zkey" "$BUILD/$CIRCUIT.zkey"
  rm -f "$BUILD/${CIRCUIT}_0.zkey"
  $SNARKJS zkey export verificationkey "$BUILD/$CIRCUIT.zkey" "$BUILD/$CIRCUIT.vkey.json"
  echo "  -> $BUILD/$CIRCUIT.zkey + $CIRCUIT.vkey.json"
done

echo "done. vkey is committed; zkey is gitignored + regenerated by this script."
