#!/usr/bin/env bash
# Groth16 setup for the Sefi circom recipe circuits.
#
# NOTE: snarkjs `contribute` mixes OS randomness, so this is NOT bit-for-bit
# reproducible. That is fine because every Sefi flow derives the on-chain
# verification key from the CURRENT zkey at runtime (see groth16ToSoroban), so
# the proving key and verifying key are always a matched pair. The canonical
# BLEND artifacts are committed as a matched set; this script (re)builds any
# circuit's zkey+vkey together.
#
#   pnpm circom:setup                                   # all recipe circuits
#   SEFI_CIRCUITS=blend_utilization  pnpm circom:setup
#   SEFI_CIRCUITS=aquarius_route      pnpm circom:setup
#   SEFI_CIRCUITS=sdex_exit           pnpm circom:setup
#   SEFI_CIRCUITS=composite_borrow_exit pnpm circom:setup
#   SEFI_CIRCUITS=all                 pnpm circom:setup   # (same as default)
set -euo pipefail

CIRCOM_DIR="circuits/circom"
BUILD="$CIRCOM_DIR/build"
PTAU_POWER="${SEFI_PTAU_POWER:-16}"
# All Phase 3 recipe circuits. `all` (or unset) builds every one.
ALL_CIRCUITS="blend_utilization aquarius_route sdex_exit composite_borrow_exit"
mkdir -p "$BUILD"

if ! command -v circom >/dev/null 2>&1; then
  echo "FAIL: circom not found; install circom 2.x (cargo install --git https://github.com/iden3/circom)"; exit 1
fi
SNARKJS="npx snarkjs"
if ! node -e "require.resolve('snarkjs')" >/dev/null 2>&1; then
  echo "FAIL: snarkjs not found; run 'pnpm install'"; exit 1
fi

# 1) One shared powers-of-tau (deterministic: fixed entropy + beacon).
PTAU="$BUILD/pot_final.ptau"
if [ ! -f "$PTAU" ]; then
  echo "== powers of tau (2^$PTAU_POWER, deterministic) =="
  $SNARKJS powersoftau new bn128 "$PTAU_POWER" "$BUILD/pot_0.ptau" -v
  $SNARKJS powersoftau contribute "$BUILD/pot_0.ptau" "$BUILD/pot_1.ptau" \
    --name="sefi-fixed" -e="sefi-deterministic-ptau-entropy"
  $SNARKJS powersoftau beacon "$BUILD/pot_1.ptau" "$BUILD/pot_beacon.ptau" \
    0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20 10 -n="sefi beacon"
  $SNARKJS powersoftau prepare phase2 "$BUILD/pot_beacon.ptau" "$PTAU" -v
  rm -f "$BUILD/pot_0.ptau" "$BUILD/pot_1.ptau" "$BUILD/pot_beacon.ptau"
fi

# SEFI_CIRCUITS overrides the circuit list (e.g. CI builds only blend for speed).
# "all" (or unset) builds every recipe circuit.
SELECTED="${SEFI_CIRCUITS:-all}"
if [ "$SELECTED" = "all" ]; then SELECTED="$ALL_CIRCUITS"; fi

for CIRCUIT in $SELECTED; do
  echo "== $CIRCUIT =="
  if [ ! -f "$CIRCOM_DIR/$CIRCUIT.circom" ]; then
    echo "FAIL: circuit source $CIRCOM_DIR/$CIRCUIT.circom not found"; exit 1
  fi
  circom "$CIRCOM_DIR/$CIRCUIT.circom" --r1cs --wasm --sym \
    -l node_modules/circomlib/circuits -o "$BUILD"
  $SNARKJS groth16 setup "$BUILD/$CIRCUIT.r1cs" "$PTAU" "$BUILD/${CIRCUIT}_0.zkey"
  $SNARKJS zkey contribute "$BUILD/${CIRCUIT}_0.zkey" "$BUILD/$CIRCUIT.zkey" \
    --name="sefi-fixed" -e="sefi-deterministic-zkey-entropy-$CIRCUIT"
  $SNARKJS zkey beacon "$BUILD/$CIRCUIT.zkey" "$BUILD/${CIRCUIT}_final.zkey" \
    0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20 10 -n="sefi zkey beacon"
  mv "$BUILD/${CIRCUIT}_final.zkey" "$BUILD/$CIRCUIT.zkey"
  rm -f "$BUILD/${CIRCUIT}_0.zkey"
  $SNARKJS zkey export verificationkey "$BUILD/$CIRCUIT.zkey" "$BUILD/$CIRCUIT.vkey.json"
  # Fail loudly if the vkey did not materialise.
  if [ ! -s "$BUILD/$CIRCUIT.vkey.json" ]; then
    echo "FAIL: verification key for $CIRCUIT was not generated"; exit 1
  fi
  echo "  -> $BUILD/$CIRCUIT.zkey + $CIRCUIT.vkey.json"
done

echo "done. vkey is committed; zkey is gitignored + regenerated by this script."
