import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { ProofEnvelope } from "@sefi/shared-types";
import { buildProofEnvelope } from "./envelope.js";
import type { ProofRequest } from "./backends.js";
import { buildWitness, witnessToCircomInput, referenceEvaluate } from "./witness.js";

/**
 * bn254-groth16 backend (audit follow-up: Option B).
 *
 * Generates a REAL Groth16/BN254 proof for the actual Sefi ComputeIntent using
 * snarkjs over the circom recipe circuits. The circuit uses the same circomlib
 * Poseidon as the TS zkFactsRoot/zkContextRoot, so the proof verifies against
 * the exact roots the capsule already commits. The same proof verifies on the
 * Soroban BN254 verifier (Groth16), enabling genuine `stellar_verified` for Sefi
 * compute proofs — not a separate test proof.
 *
 * Artifacts live under circuits/circom/build/<recipe>.{wasm,zkey,vkey.json}.
 * The wasm + vkey are committed; the zkey is regenerated by `pnpm circom:setup`
 * (it is large and gitignored). Proving requires the zkey to be present.
 */

const RECIPE_CIRCUIT: Record<string, string> = {
  "blend-utilization-policy": "blend_utilization",
};

export class Groth16NotAvailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "Groth16NotAvailableError";
  }
}

function buildDir(): string {
  return process.env.SEFI_CIRCOM_BUILD || join(process.cwd(), "circuits/circom/build");
}

function artifacts(recipe: string) {
  const circuit = RECIPE_CIRCUIT[recipe];
  if (!circuit)
    throw new Groth16NotAvailableError(
      `SEFI_GROTH16_NO_CIRCUIT: no circom circuit for recipe "${recipe}"`,
    );
  const dir = buildDir();
  return {
    circuit,
    wasm: join(dir, `${circuit}_js`, `${circuit}.wasm`),
    zkey: join(dir, `${circuit}.zkey`),
    vkey: join(dir, `${circuit}.vkey.json`),
  };
}

export function groth16ArtifactsReady(recipe: string): boolean {
  try {
    const a = artifacts(recipe);
    return existsSync(a.wasm) && existsSync(a.zkey) && existsSync(a.vkey);
  } catch {
    return false;
  }
}

/**
 * The proof public signals (snarkjs order): [safe, zkContextRoot, zkFactsRoot,
 * computeHash, resultHash]. Stored on the envelope so the on-chain verifier and
 * verifyLocal can use them directly.
 */
export interface Groth16Artifact {
  proof: unknown;
  publicSignals: string[];
}

export async function proveGroth16(input: ProofRequest): Promise<ProofEnvelope> {
  const recipe = input.compiled.name;
  const a = artifacts(recipe);
  if (!existsSync(a.wasm) || !existsSync(a.zkey)) {
    throw new Groth16NotAvailableError(
      `SEFI_GROTH16_ARTIFACTS_MISSING: ${a.zkey} not found. Run \`pnpm circom:setup\` to (re)generate the proving key. This backend never silently falls back.`,
    );
  }

  // Build the complete witness and validate it against the reference circuit.
  const witness = buildWitness({
    recipe,
    compiled: input.compiled,
    capsule: input.capsule,
    facts: input.facts,
    evaluation: input.evaluation,
    privateInputs: input.privateInputs,
  });
  const ref = referenceEvaluate(recipe, witness.facts, witness.thresholds, {
    zkContextRoot: witness.public.zkContextRoot,
    zkFactsRoot: witness.public.zkFactsRoot,
    sourceRoot: witness.public.sourceRoot,
    adapterSetHash: witness.public.adapterSetHash,
  });
  if (!ref.contextRootOk || !ref.merkleOk)
    throw new Groth16NotAvailableError(
      `SEFI_GROTH16_WITNESS_INVALID: contextRootOk=${ref.contextRootOk} merkleOk=${ref.merkleOk}`,
    );

  const snarkjs = (await import(/* webpackIgnore: true */ "snarkjs" as string)) as any;
  const { groth16 } = snarkjs;
  const circomInput = witnessToCircomInput(witness);
  const { proof, publicSignals } = await groth16.fullProve(circomInput, a.wasm, a.zkey);

  // Local sanity verification before emitting.
  const vkey = JSON.parse(await readFile(a.vkey, "utf8"));
  const ok = await groth16.verify(vkey, publicSignals, proof);
  await terminateCurve();
  if (!ok) throw new Groth16NotAvailableError("SEFI_GROTH16_LOCAL_VERIFY_FAILED");

  const envelope = buildProofEnvelope({
    backend: "bn254-groth16",
    compiled: input.compiled,
    evaluation: input.evaluation,
    proofBytes: Buffer.from(JSON.stringify(proof)).toString("base64"),
  });
  // Attach the snarkjs artifacts (used by verifyLocal + the Soroban verifier).
  envelope.groth16 = { proof, publicSignals, vkey };
  return envelope;
}

/** 32-byte big-endian hex (no 0x) for a decimal field string. */
function fieldBe(dec: string): string {
  return BigInt(dec).toString(16).padStart(64, "0");
}

/**
 * Serialize a snarkjs Groth16 proof + vkey + public signals into the Soroban
 * BN254 verifier's EIP-197 byte layout (audit follow-up: verify the ACTUAL Sefi
 * compute proof on-chain). G1 = be(x)||be(y); G2 = be(x.c1)||be(x.c0)||be(y.c1)||be(y.c0).
 *
 * snarkjs proof: pi_a (G1, 3 coords incl. z=1), pi_b (G2, [[x0,x1],[y0,y1],[1,0]]),
 * pi_c (G1). snarkjs vkey: vk_alpha_1 (G1), vk_beta_2 (G2), vk_gamma_2 (G2),
 * vk_delta_2 (G2), IC (G1[]). snarkjs G2 fp2 is [c0, c1] (real, imaginary).
 */
export function groth16ToSoroban(g: {
  proof: any;
  publicSignals: string[];
  vkey: any;
}): {
  proof: { a: string; b: string; c: string };
  vk: { alpha_g1: string; beta_g2: string; gamma_g2: string; delta_g2: string; ic: string[] };
  publicInputs: string[];
} {
  const g1 = (p: any[]): string => fieldBe(p[0]) + fieldBe(p[1]);
  // snarkjs fp2 coords are [c0, c1]; EIP-197 wants c1 (imaginary) first.
  const g2 = (p: any[][]): string =>
    fieldBe(p[0][1]) + fieldBe(p[0][0]) + fieldBe(p[1][1]) + fieldBe(p[1][0]);

  const v = g.vkey;
  return {
    proof: { a: g1(g.proof.pi_a), b: g2(g.proof.pi_b), c: g1(g.proof.pi_c) },
    vk: {
      alpha_g1: g1(v.vk_alpha_1),
      beta_g2: g2(v.vk_beta_2),
      gamma_g2: g2(v.vk_gamma_2),
      delta_g2: g2(v.vk_delta_2),
      ic: v.IC.map((p: any[]) => g1(p)),
    },
    // Public inputs are the snarkjs publicSignals (each a decimal field string).
    publicInputs: g.publicSignals.map((s) => fieldBe(s)),
  };
}

/** Verify a bn254-groth16 envelope with snarkjs (real cryptographic verification). */
export async function verifyGroth16Local(envelope: ProofEnvelope): Promise<boolean> {
  const g = envelope.groth16 as (Groth16Artifact & { vkey?: unknown }) | undefined;
  if (!g?.proof || !g.publicSignals || !g.vkey) return false;
  const { groth16 } = (await import(/* webpackIgnore: true */ "snarkjs" as string)) as any;
  const ok = await groth16.verify(g.vkey, g.publicSignals, g.proof);
  await terminateCurve();
  return ok;
}

/**
 * snarkjs spins up a global bn128 curve backed by worker threads and reuses it
 * across calls. Under back-to-back prove/verify calls those workers can race;
 * terminating the curve after each op makes the path deterministic (and lets the
 * process exit cleanly). Safe to call when no curve exists.
 */
async function terminateCurve(): Promise<void> {
  try {
    const g = globalThis as any;
    if (g.curve_bn128 && typeof g.curve_bn128.terminate === "function") {
      await g.curve_bn128.terminate();
      g.curve_bn128 = null;
    }
  } catch {
    /* best effort */
  }
}
